### ISSUE TITLE
Release on NPM

### ISSUE THREAD

**Issue by garrettw** [mcaskill/sass-mq#1]
Could you tweak the package name and release this on NPM? I'd love to be able to use it as a dependency rather than having to manually download it.

**Comment by mcaskill** [comment]
Hi @garrettw 

Thanks for your interest in my fork. I haven't used sass-mq in a while but I have begun the process of updating it to support the latest releases.

I will attempt to publish it cleanly to NPM. It will be named `@mcaskill/sass-mq` and it will be tagged as one minor version ahead of Kaelig's latest release (so if @sass-mq/sass-mq is v5.0.2, mine will be v5.1.2).

I'll keep you posted.

**Comment by mcaskill** [comment]
Hi @garrettw 

I've finally published the fork to NPM: [@mcaskill/sass-mq](https://www.npmjs.com/package/@mcaskill/sass-mq)

**Comment by garrettw** [comment]
Awesome! Hope you get some new exposure out of it :)
