### ISSUE TITLE
Support for `@use` syntax

### ISSUE THREAD

**Issue by vasartam** [mcaskill/sass-mq#2]
First of all, thanks for a good fork. The feature with `$or` parameter helped me a lot in one of my previous projects.

However, the current way of importing the library into the project was deprecated at October 2021 and is planned for removal, according to official Sass docs:
https://github.com/sass/sass/blob/main/accepted/module-system.md#timeline
https://sass-lang.com/documentation/at-rules/import

It is not currently possible to `@use` this library, because my Sass compiler (Dart Sass) throws this error:
```
ERROR in ./assets/styles/style.scss (./assets/styles/style.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].use[2]!./assets/styles/style.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: This variable was not declared with !default in the @used module.
   ╷
43 │   $breakpoints: $breakpoints,
   │   ^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  assets/styles/_vars.scss 43:3  @import
  assets/styles/style.scss 4:9   root stylesheet
 @ ./assets/styles/style.scss
 @ ./assets/js/index.js 1:0-30
```

The code for `@use`-ing the library is as follows:
```scss
$breakpoints: (
	mobile: 375px,
	tablet: 768px,
	desktop: 1440px,
	hd: 1920px,
);

$breakpoints-shown: (mobile, tablet, desktop, hd);

@use "~@mcaskill/sass-mq" with (
	$breakpoints: $breakpoints,
	$show-breakpoints: $breakpoints-shown,
);
```

The main repo of `sass-mq` library did already switch to `@use` syntax, according to their example in README:
https://github.com/sass-mq/sass-mq#how-to-use-it

It would be great if this fork supported the `@use` syntax. Possibly, it is much simpler to just merge the changes from the main `sass-mq` repo?

Thanks in advance!

**Comment by vasartam** [comment]
Resolved the issue by specifying parameter names as they are defined into the main `_mq.scss` file:
```scss
// _vars.scss:

$mq-breakpoints: (
	mobile: 375px,
	tablet: 768px,
	desktop: 1440px,
	hd: 1920px,
);

$mq-show-breakpoints: (mobile, tablet, desktop, hd);

// style.scss:

@use "vars" as v;
@use "~@mcaskill/sass-mq" with (
	$mq-breakpoints: v.$mq-breakpoints,
	$mq-show-breakpoints: v.$mq-show-breakpoints,
);
```

Renaming local variables wasn't necessary, but I did it for convenience.
Also was having issues on `@use "~@mcaskill/sass-mq" with (...)` - had to move it into the main file for `sass-mq` to be configured only once. `@use`-ing the library in other files then should be done without `with`:
```scss
@use "~@mcaskill/sass-mq" as mq;

.selector {
	@include mq.mq($from: tablet, $media-type: screen) {
		margin-top: 2rem;
	}
}
```

**Comment by mcaskill** [comment]
Sorry for the belated maintenance. I've finally upgraded the codebase to [v6.0.0](https://www.npmjs.com/package/@mcaskill/sass-mq/v/6.0.0).
